#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Pavithra dev blog

# Short bio or description (displayed in the header)
description: Java Learning Series
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmip36W3Bdgf0agj-xK896ACRBwR1bJ0WUTA&s

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: https://github.com/pavithra086
  instagram:
  linkedin: www.linkedin.com/in/pavithra-n0867
  pinterest:
  
  
 
